# GitHub Actions

name: example-basic
# This workflow represents a set of basic End-to-End tests
on:
  push:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create a file
        run: echo "I won't live long" > my_file.txt
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: my_file.txt
          retention-days: 90
