# GitHub Actions

name: get-repository-clones

on:
  push:
  workflow_dispatch:

jobs:
  get_stats:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Get stats
        run: |
          gh api --header 'Accept: application/vnd.github+json' https://api.github.com/repos/$OWNER/$REPO/traffic/views
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
