# GitHub Actions

name: get-repository-clones

on:
  push:
  workflow_dispatch:

jobs:
  get_stats:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Get stats
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/flakysilence/myrepo1/traffic/views
